# Generated by Django 5.2.1 on 2025-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField()),
                ('option_id', models.IntegerField()),
                ('voter_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['poll_id'], name='idx_vote_log_poll'), models.Index(fields=['option_id'], name='idx_vote_log_option')],
            },
        ),
    ]
