# Generated by Django 5.2.1 on 2025-05-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_logs', to='polls.option')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_logs', to='polls.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll_id', 'voter_name'], name='polls_votel_poll_id_b0ecb3_idx')],
                'unique_together': {('poll_id', 'voter_name')},
            },
        ),
    ]
