# Generated by Django 5.2.1 on 2025-05-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_votelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteLog',
        ),
    ]
