# Generated by Django 5.2.1 on 2025-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_votelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
